=== Lafayette21/WT_2021-22/Lab02/plik.dtd
<!ELEMENT uczelnia (wydzial+)>
<!ELEMENT wydzial (nazwa, kierunek+)>
<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT kierunek (nazwa,student+)>
<!ELEMENT student (imie+,nazwisko,nralbumu)>
<!ELEMENT imie (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT nralbumu (#PCDATA)>

=== Lafayette21/WT_2021-22/Lab02/plik.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE uczelnia SYSTEM "plik.dtd">
<uczelnia>
  <wydzial>
    <nazwa>Fizyki i Informatyki Stosowanej</nazwa>
    <kierunek>
      <nazwa>Informatyka Stosowana</nazwa>
      <student>
        <imie>Marcin</imie>
        <nazwisko>Urbanowicz</nazwisko>
        <nralbumu>123</nralbumu>
      </student>
      <student>
        <imie>Robert</imie>
        <nazwisko>Głowacki</nazwisko>
        <nralbumu>245</nralbumu>
      </student>
      <student>
        <imie>Jan</imie>
        <nazwisko>Niezbedny</nazwisko>
        <nralbumu>150</nralbumu>
      </student>
    </kierunek>
    <kierunek>
      <nazwa>Fizyka Techniczna</nazwa>
      <student>
        <imie>Adam</imie>
        <nazwisko>Słonko</nazwisko>
        <nralbumu>223</nralbumu>
      </student>
      <student>
        <imie>Robert</imie>
        <nazwisko>Romanowski</nazwisko>
        <nralbumu>249</nralbumu>
      </student>
      <student>
        <imie>Michał</imie>
        <nazwisko>Pieróg</nazwisko>
        <nralbumu>370</nralbumu>
      </student>
    </kierunek>
  </wydzial>
</uczelnia>
